theme: jekyll-theme-cayman
title: Multi-timescale Trajectory Prediction for Abnormal Human Activity Detection
description: Royston Rodrigues, Neha Bhargava, Rajbabu Velmurugan, Subhasis Chaudhuri
github:
 repository_url: http://example.com
github:
 zip_url: www.gmail.com
 another_url: www.gmail.com
