theme: jekyll-theme-cayman
title: Multi-timescale Trajectory Prediction for Abnormal Human Activity Detection
description: Indian Institute of Technology Bombay
 arxiv: http://openaccess.thecvf.com/content_WACV_2020/html/Rodrigues_Multi-timescale_Trajectory_Prediction_for_Abnormal_Human_Activity_Detection_WACV_2020_paper.html


