theme: jekyll-theme-cayman
title: Multi-timescale Trajectory Prediction \n
for \n
Abnormal Human Activity Detection
description: Royston Rodrigues
github:
  zip_url: www.gmail.com
  another_url: www.gmail.com
