theme: jekyll-theme-cayman
title: Multi-timescale Trajectory Prediction for Abnormal Human Activity Detection
description: Royston Rodrigues, Neha Bhargava, Rajbabu Velmurugan, Subhasis Chaudhuri
github:
 repository_url: https://github.com/Rodrigues-Royston/Multi-timescale-Trajectory-Prediction-for-Abnormal-Human-Activity-Detection/blob/master/README.md
 arxiv: http://example.com


